name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  # One workflow run at a time per branch.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    outputs:
      dist: ${{ steps.filter.outputs.dist }}
      ci: ${{ steps.filter.outputs.ci }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        id: setup-pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v6
        with:
          node-version-file: .tool-versions
          cache: pnpm

      - name: Install Dependencies
        id: pnpm-install
        run: pnpm install --frozen-lockfile

      - name: Format Check
        id: format-check
        run: pnpm format:check

      - name: Lint Check
        id: lint-check
        run: pnpm lint

      - name: dist Check
        id: dist-check
        run: scripts/check_dist.sh

      - name: Detect dist Changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            dist:
              - 'dist/**'
            ci:
              - '.github/workflows/ci.yml'

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    needs: test-typescript
    # Only run when dist or workflow has benn changed and disable on PR without write permissions
    if: |
      (needs.test-typescript.outputs.dist == 'true' || needs.test-typescript.outputs.ci == 'true') && 
      github.event.pull_request.head.repo.full_name == github.repository && 
      github.actor != 'dependabot[bot]'

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Set Up Test Files
        id: setup-test-files
        env:
          TEST_DIR: ./test_files
        run: |
          DATE=$(date --iso-8601=seconds)
          mkdir -p $TEST_DIR
          echo "Upload file 1 $DATE" > $TEST_DIR/upload-1.txt
          echo "Upload file 2 $DATE" > $TEST_DIR/upload-2.txt
          echo "Not upload file 1 $DATE" > $TEST_DIR/not-upload-1.txt

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          bduss: ${{ secrets.BDUSS }}
          stoken: ${{ secrets.STOKEN }}
          target: "./test_files/upload*"
          remote-dir: "/baidu-netdisk-upload-action-test/"
          upload-policy: "overwrite"

      - name: Verify Results
        id: verify-results
        # BaiduPCS-Go has been logged in through the action above
        run: |
          BAIDUPCS_GO_EXECUTABLE=$(find ./baidupcs -name BaiduPCS-Go)
          DATE=$(TZ=Asia/Shanghai date +%F)
          LS_OUTPUT=$($BAIDUPCS_GO_EXECUTABLE ls /baidu-netdisk-upload-action-test/)
          grep --quiet "$DATE.*upload-1.txt" <<< "$LS_OUTPUT"
          grep --quiet "$DATE.*upload-2.txt" <<< "$LS_OUTPUT"
          grep --quiet --invert-match "not-upload-1.txt" <<< "$LS_OUTPUT"
